### PR TITLE
Use Scratch 1.4 drums instead of Scratch 2.0 drums

### PR DESCRIPTION
**Pull request by DevanWolf**
For use with an updated version of the MIDI importer project.

### CODE REVIEW

**Comment by ed-cooper** [comment]
Hi! Thanks for taking some interest!

You raise an interesting idea here and it works well considering the note numbers then line up directly to the Scratch drums.

I've noticed that you've also deleted the `<summary>` and `</summary>` comment tags. These should be kept as they are used by Visual Studio (as well as possibly some other IDEs) to generate an XML documentation file for the library.

**Comment by DevanWolf** [comment]
Okay, I updated my file. I put the summaries back.

**Comment by DevanWolf** [comment]
Did you release my fork yet please?

**Comment by ed-cooper** [comment]
Sorry - had forgotten.
I've just merged this and updated the main project and I'll set about getting everything else compatible asap

**Comment by ed-cooper** [comment]
Hmmm. Sorry - had to revert the changes ☹️

Your code does work, however, after some brief testing on the Scratch side I found that using the legacy "play drum" blocks from Scratch 1.4 caused other notes to stop playing when lots of notes are playing

This caused particularly noticeable issues in the demo goldfinger midi file

**Comment by DevanWolf** [comment]
Can you at least make an "auto-panic" like when the current playing notes reach 32, all notes are being killed so new notes can be played? Then you can be able to use the Scratch 1.4 "play drum" block.
BTW, Scratch 1.4 drums work well in MIDI songs.
My test version is how "auto-panic" should work: http://scratch.mit.edu/projects/112742767#editor

**Pull request merged**
